-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.offers (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  network text,
  title text,
  description text,
  price numeric,
  CONSTRAINT offers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.orders (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid DEFAULT gen_random_uuid(),
  user_name text,
  user_email text,
  phone text,
  offer_title text,
  amount numeric,
  network text,
  status text,
  payment_reference text,
  is_self boolean,
  data_amount text,
  offer_id bigint,
  bank text,
  channel text,
  country_code text,
  paystack_transaction_id text,
  paystack_transaction_status text,
  paid_at timestamp with time zone,
  device_token text,
  jehuca_order_id text,
  jehuca_order_status text,
  jehuca_response jsonb,
  buyer_type text CHECK (buyer_type IS NULL OR (buyer_type = ANY (ARRAY['normal_user'::text, 'sub_agent'::text, 'super_agent'::text]))),
  provider_package_id text,
  provider_type text,
  provider_size numeric,
  base_amount numeric DEFAULT 0,
  agent_markup numeric DEFAULT 0,
  transaction_fee numeric DEFAULT 0,
  main_account_amount numeric DEFAULT 0,
  provider_deferred_at timestamp with time zone,
  provider_deferred_reason text,
  provider_dispatch_attempts integer NOT NULL DEFAULT 0,
  api_cost numeric,
  cost_source text,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.offers(id)
);
CREATE TABLE public.agent_offers (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  network text,
  title text,
  description text,
  price numeric,
  CONSTRAINT agent_offers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.agent_orders (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  agent_id uuid DEFAULT gen_random_uuid(),
  offer_id bigint,
  offer_title text,
  network text,
  amount numeric,
  recipient_phone text,
  recipient_name text,
  status text,
  transaction_status text,
  channel text,
  device_token text,
  super_agent_id uuid,
  admin_share numeric DEFAULT 0,
  super_agent_share numeric DEFAULT 0,
  agent_net numeric DEFAULT 0,
  settlement_status text NOT NULL DEFAULT 'pending'::text CHECK (settlement_status = ANY (ARRAY['pending'::text, 'settled'::text, 'released'::text, 'failed'::text])),
  paystack_subaccount_code text,
  paystack_transaction_id text,
  paystack_transaction_status text,
  paid_at timestamp with time zone,
  bank text,
  jehuca_order_id text,
  jehuca_order_status text,
  jehuca_response jsonb,
  base_amount numeric DEFAULT 0,
  agent_markup numeric DEFAULT 0,
  transaction_fee numeric DEFAULT 0,
  main_account_amount numeric DEFAULT 0,
  provider_package_id text,
  provider_type text,
  provider_size numeric,
  buyer_type text CHECK (buyer_type IS NULL OR (buyer_type = ANY (ARRAY['normal_user'::text, 'sub_agent'::text, 'super_agent'::text]))),
  provider_deferred_at timestamp with time zone,
  provider_deferred_reason text,
  provider_dispatch_attempts integer NOT NULL DEFAULT 0,
  api_cost numeric,
  cost_source text,
  payment_reference text,
  held_at timestamp with time zone,
  held_expires_at timestamp with time zone,
  expired_at timestamp with time zone,
  expiry_reason text,
  refund_required boolean NOT NULL DEFAULT false,
  CONSTRAINT agent_orders_pkey PRIMARY KEY (id),
  CONSTRAINT agent_orders_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.agent_offers(id),
  CONSTRAINT agent_orders_super_agent_id_fkey FOREIGN KEY (super_agent_id) REFERENCES auth.users(id)
);
CREATE TABLE public.agent_wallet (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  agent_id uuid DEFAULT 'cf772940-e18d-4fd9-bdbf-8ffdcfe05b98'::uuid,
  account_uuid uuid DEFAULT gen_random_uuid(),
  balance numeric,
  CONSTRAINT agent_wallet_pkey PRIMARY KEY (id),
  CONSTRAINT agent_wallet_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id)
);
CREATE TABLE public.notifications (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_id uuid DEFAULT 'cf772940-e18d-4fd9-bdbf-8ffdcfe05b98'::uuid,
  message text,
  created_at timestamp with time zone DEFAULT now(),
  status text,
  read boolean DEFAULT false,
  title text,
  type text DEFAULT 'notification'::text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ads (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  title text NOT NULL,
  description text,
  image_url text,
  action_text text DEFAULT 'Learn More'::text,
  action_url text,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  start_date timestamp with time zone DEFAULT now(),
  end_date timestamp with time zone,
  target_audience text,
  priority integer DEFAULT 1,
  click_count integer DEFAULT 0,
  impression_count integer DEFAULT 0,
  website_url text,
  CONSTRAINT ads_pkey PRIMARY KEY (id)
);
CREATE TABLE public.app_versions (
  id integer NOT NULL DEFAULT nextval('app_versions_id_seq'::regclass),
  platform character varying NOT NULL CHECK (platform::text = ANY (ARRAY['ios'::character varying, 'android'::character varying, 'web'::character varying]::text[])),
  current_version character varying NOT NULL,
  minimum_version character varying,
  is_update_required boolean DEFAULT false,
  update_url text,
  download_url text,
  release_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT app_versions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.wallet_topups (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  agent_id uuid NOT NULL,
  amount numeric NOT NULL,
  reference text NOT NULL UNIQUE,
  paystack_transaction_id text,
  paystack_transaction_status text,
  paid_at timestamp with time zone,
  channel text,
  bank text,
  status text DEFAULT 'pending'::text,
  paystack_subaccount_code text,
  gross_amount numeric,
  charge_amount numeric,
  charge_percent numeric,
  funder_user_id uuid,
  wallet_owner_id uuid,
  CONSTRAINT wallet_topups_pkey PRIMARY KEY (id),
  CONSTRAINT wallet_topups_funder_user_id_fkey FOREIGN KEY (funder_user_id) REFERENCES auth.users(id),
  CONSTRAINT wallet_topups_wallet_owner_id_fkey FOREIGN KEY (wallet_owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_push_tokens (
  id integer NOT NULL DEFAULT nextval('user_push_tokens_id_seq'::regclass),
  user_id uuid DEFAULT 'cf772940-e18d-4fd9-bdbf-8ffdcfe05b98'::uuid,
  push_token text NOT NULL,
  platform text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  token_type text DEFAULT 'expo'::text,
  CONSTRAINT user_push_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT user_push_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.admin_push_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL DEFAULT 'cf772940-e18d-4fd9-bdbf-8ffdcfe05b98'::uuid,
  push_token text NOT NULL,
  platform text NOT NULL CHECK (platform = ANY (ARRAY['ios'::text, 'android'::text, 'web'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  token_type text DEFAULT 'expo'::text,
  CONSTRAINT admin_push_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT admin_push_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.ussd_agents (
  id bigint NOT NULL DEFAULT nextval('ussd_agents_id_seq'::regclass),
  agent_id uuid NOT NULL UNIQUE,
  msisdn text NOT NULL UNIQUE CHECK (msisdn ~ '^\+233[2356789][0-9]{8}$'::text),
  pin_hash text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ussd_agents_pkey PRIMARY KEY (id),
  CONSTRAINT ussd_agents_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id)
);
CREATE TABLE public.super_agent_offers (
  id bigint NOT NULL DEFAULT nextval('super_agent_offers_id_seq'::regclass),
  super_agent_id uuid NOT NULL,
  title text NOT NULL,
  network text NOT NULL,
  data_value text NOT NULL,
  price numeric NOT NULL CHECK (price > 0::numeric),
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  tier_name text,
  default_tier_name text,
  tier_description text,
  CONSTRAINT super_agent_offers_pkey PRIMARY KEY (id),
  CONSTRAINT super_agent_offers_super_agent_id_fkey FOREIGN KEY (super_agent_id) REFERENCES auth.users(id)
);
CREATE TABLE public.super_agent_assignments (
  id bigint NOT NULL DEFAULT nextval('super_agent_assignments_id_seq'::regclass),
  super_agent_id uuid NOT NULL,
  agent_id uuid NOT NULL,
  offer_id bigint NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  tier_name text,
  agent_price numeric,
  CONSTRAINT super_agent_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT super_agent_assignments_super_agent_id_fkey FOREIGN KEY (super_agent_id) REFERENCES auth.users(id),
  CONSTRAINT super_agent_assignments_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id),
  CONSTRAINT super_agent_assignments_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.super_agent_offers(id)
);
CREATE TABLE public.agent_payment_settlements (
  id bigint NOT NULL DEFAULT nextval('agent_payment_settlements_id_seq'::regclass),
  agent_order_id bigint,
  agent_id uuid NOT NULL,
  super_agent_id uuid NOT NULL,
  admin_id uuid,
  gross_amount numeric NOT NULL,
  super_agent_share numeric NOT NULL DEFAULT 0,
  admin_share numeric NOT NULL DEFAULT 0,
  agent_net numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'settled'::text, 'released'::text, 'failed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agent_payment_settlements_pkey PRIMARY KEY (id),
  CONSTRAINT agent_payment_settlements_agent_order_id_fkey FOREIGN KEY (agent_order_id) REFERENCES public.agent_orders(id),
  CONSTRAINT agent_payment_settlements_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES auth.users(id),
  CONSTRAINT agent_payment_settlements_super_agent_id_fkey FOREIGN KEY (super_agent_id) REFERENCES auth.users(id),
  CONSTRAINT agent_payment_settlements_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES auth.users(id)
);
CREATE TABLE public.super_agent_tiers (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  super_agent_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT super_agent_tiers_pkey PRIMARY KEY (id),
  CONSTRAINT super_agent_tiers_super_agent_id_fkey FOREIGN KEY (super_agent_id) REFERENCES auth.users(id)
);
CREATE TABLE public.super_agent_paystack (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  super_agent_id uuid NOT NULL UNIQUE,
  subaccount_code text NOT NULL,
  business_name text,
  settlement_bank text,
  settlement_bank_code text,
  account_number text,
  percentage_charge numeric,
  is_active boolean NOT NULL DEFAULT true,
  paystack_raw_response jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT super_agent_paystack_pkey PRIMARY KEY (id),
  CONSTRAINT super_agent_paystack_super_agent_id_fkey FOREIGN KEY (super_agent_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  role text NOT NULL DEFAULT 'normal_user'::text CHECK (role = ANY (ARRAY['normal_user'::text, 'super_agent'::text, 'sub_agent'::text, 'admin'::text])),
  super_agent_id uuid,
  business_name text,
  full_name text,
  email text,
  phone text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT user_profiles_super_agent_id_fkey FOREIGN KEY (super_agent_id) REFERENCES auth.users(id)
);
CREATE TABLE public.package_pricing (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  network text NOT NULL,
  type text NOT NULL,
  base_price numeric NOT NULL DEFAULT 0 CHECK (base_price >= 0::numeric),
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  package_id text,
  size numeric,
  CONSTRAINT package_pricing_pkey PRIMARY KEY (id),
  CONSTRAINT package_pricing_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.payment_transactions (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  order_id bigint,
  order_type text NOT NULL CHECK (order_type = ANY (ARRAY['regular'::text, 'agent'::text])),
  payment_reference text NOT NULL UNIQUE,
  paystack_transaction_id text,
  paystack_transaction_status text,
  gross_amount numeric NOT NULL DEFAULT 0,
  base_amount numeric NOT NULL DEFAULT 0,
  agent_markup numeric NOT NULL DEFAULT 0,
  transaction_fee numeric NOT NULL DEFAULT 0,
  main_account_amount numeric NOT NULL DEFAULT 0,
  super_agent_amount numeric NOT NULL DEFAULT 0,
  agent_net numeric NOT NULL DEFAULT 0,
  super_agent_id uuid,
  settlement_status text NOT NULL DEFAULT 'pending'::text CHECK (settlement_status = ANY (ARRAY['pending'::text, 'settled'::text, 'released'::text, 'failed'::text])),
  status text NOT NULL DEFAULT 'success'::text,
  network text,
  offer_title text,
  recipient_phone text,
  channel text,
  bank text,
  paystack_subaccount_code text,
  jehuca_order_id text,
  jehuca_order_status text,
  jehuca_response jsonb,
  buyer_type text CHECK (buyer_type IS NULL OR (buyer_type = ANY (ARRAY['normal_user'::text, 'sub_agent'::text, 'super_agent'::text]))),
  CONSTRAINT payment_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT payment_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT payment_transactions_super_agent_id_fkey FOREIGN KEY (super_agent_id) REFERENCES auth.users(id)
);
CREATE TABLE public.super_agent_wallets (
  super_agent_id uuid NOT NULL,
  balance numeric NOT NULL DEFAULT 0 CHECK (balance >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT super_agent_wallets_pkey PRIMARY KEY (super_agent_id),
  CONSTRAINT super_agent_wallets_super_agent_id_fkey FOREIGN KEY (super_agent_id) REFERENCES auth.users(id)
);
CREATE TABLE public.super_agent_wallet_ledger (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  super_agent_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount <> 0::numeric),
  balance_before numeric NOT NULL,
  balance_after numeric NOT NULL CHECK (balance_after >= 0::numeric),
  entry_type text NOT NULL CHECK (entry_type = ANY (ARRAY['credit'::text, 'debit'::text])),
  reason text NOT NULL,
  reference text NOT NULL UNIQUE,
  order_id bigint,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT super_agent_wallet_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT super_agent_wallet_ledger_super_agent_id_fkey FOREIGN KEY (super_agent_id) REFERENCES auth.users(id)
);
CREATE TABLE public.payment_charge_settings (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  normal_user_percent numeric NOT NULL DEFAULT 1.95,
  super_agent_percent numeric NOT NULL DEFAULT 1.95,
  wallet_topup_percent numeric NOT NULL DEFAULT 1.95,
  updated_by uuid,
  notes text,
  CONSTRAINT payment_charge_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.normal_user_package_pricing (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  package_id text,
  network text NOT NULL,
  type text NOT NULL,
  size numeric,
  base_price numeric NOT NULL DEFAULT 0 CHECK (base_price >= 0::numeric),
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT normal_user_package_pricing_pkey PRIMARY KEY (id),
  CONSTRAINT normal_user_package_pricing_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.afa_registration_settings (
  id boolean NOT NULL DEFAULT true CHECK (id),
  registration_fee numeric NOT NULL DEFAULT 0 CHECK (registration_fee >= 0::numeric),
  currency text NOT NULL DEFAULT 'GHS'::text CHECK (currency = 'GHS'::text),
  is_enabled boolean NOT NULL DEFAULT false,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  super_agent_base_price numeric CHECK (super_agent_base_price IS NULL OR super_agent_base_price >= 0::numeric),
  sub_agent_base_price numeric CHECK (sub_agent_base_price IS NULL OR sub_agent_base_price >= 0::numeric),
  CONSTRAINT afa_registration_settings_pkey PRIMARY KEY (id),
  CONSTRAINT afa_registration_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.afa_registrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  registered_user_id uuid NOT NULL,
  payer_user_id uuid NOT NULL,
  assigned_super_agent_id uuid,
  full_name text NOT NULL,
  phone text NOT NULL,
  id_type text NOT NULL CHECK (id_type = ANY (ARRAY['National ID'::text, 'Voters ID'::text])),
  id_number text NOT NULL,
  town_city text NOT NULL,
  occupation text NOT NULL,
  additional_info jsonb NOT NULL DEFAULT '{}'::jsonb,
  fee_amount numeric NOT NULL CHECK (fee_amount >= 0::numeric),
  currency text NOT NULL DEFAULT 'GHS'::text CHECK (currency = 'GHS'::text),
  payment_method text NOT NULL CHECK (payment_method = ANY (ARRAY['paystack'::text, 'wallet'::text])),
  status text NOT NULL DEFAULT 'pending_payment'::text CHECK (status = ANY (ARRAY['pending_payment'::text, 'paid'::text, 'active'::text, 'rejected'::text, 'refunded'::text, 'cancelled'::text])),
  payment_reference text UNIQUE,
  paystack_transaction_id text,
  paystack_transaction_status text,
  paid_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  status_updated_at timestamp with time zone,
  status_updated_by uuid,
  status_note text,
  platform_fee_amount numeric CHECK (platform_fee_amount IS NULL OR platform_fee_amount >= 0::numeric),
  price_source text,
  CONSTRAINT afa_registrations_pkey PRIMARY KEY (id),
  CONSTRAINT afa_registrations_registered_user_id_fkey FOREIGN KEY (registered_user_id) REFERENCES auth.users(id),
  CONSTRAINT afa_registrations_payer_user_id_fkey FOREIGN KEY (payer_user_id) REFERENCES auth.users(id),
  CONSTRAINT afa_registrations_assigned_super_agent_id_fkey FOREIGN KEY (assigned_super_agent_id) REFERENCES auth.users(id),
  CONSTRAINT afa_registrations_status_updated_by_fkey FOREIGN KEY (status_updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.afa_payment_ledger (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  registration_id uuid NOT NULL,
  payer_user_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount <> 0::numeric),
  entry_type text NOT NULL DEFAULT 'registration_fee'::text CHECK (entry_type = ANY (ARRAY['registration_fee'::text, 'refund'::text, 'adjustment'::text])),
  payment_method text NOT NULL CHECK (payment_method = ANY (ARRAY['paystack'::text, 'wallet'::text])),
  payment_reference text NOT NULL UNIQUE,
  paystack_transaction_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  beneficiary_super_agent_id uuid,
  price_source text,
  CONSTRAINT afa_payment_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT afa_payment_ledger_registration_id_fkey FOREIGN KEY (registration_id) REFERENCES public.afa_registrations(id),
  CONSTRAINT afa_payment_ledger_payer_user_id_fkey FOREIGN KEY (payer_user_id) REFERENCES auth.users(id),
  CONSTRAINT afa_payment_ledger_beneficiary_super_agent_id_fkey FOREIGN KEY (beneficiary_super_agent_id) REFERENCES auth.users(id)
);
CREATE TABLE public.api_cost_settings (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  audience text NOT NULL DEFAULT 'super_agent'::text CHECK (audience = ANY (ARRAY['super_agent'::text, 'normal_user'::text])),
  package_id text,
  network text NOT NULL,
  type text NOT NULL,
  discount numeric NOT NULL DEFAULT 0 CHECK (discount >= 0::numeric),
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT api_cost_settings_pkey PRIMARY KEY (id),
  CONSTRAINT api_cost_settings_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.super_agent_afa_pricing (
  super_agent_id uuid NOT NULL,
  sub_agent_base_price numeric NOT NULL CHECK (sub_agent_base_price >= 0::numeric),
  currency text NOT NULL DEFAULT 'GHS'::text CHECK (currency = 'GHS'::text),
  is_enabled boolean NOT NULL DEFAULT true,
  notes text,
  updated_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT super_agent_afa_pricing_pkey PRIMARY KEY (super_agent_id),
  CONSTRAINT super_agent_afa_pricing_super_agent_id_fkey FOREIGN KEY (super_agent_id) REFERENCES auth.users(id),
  CONSTRAINT super_agent_afa_pricing_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.edge_function_logs (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  function_name text NOT NULL,
  request_id text NOT NULL,
  user_id uuid,
  user_role text,
  method text NOT NULL,
  status_code integer NOT NULL,
  duration_ms integer,
  error_kind text NOT NULL DEFAULT 'ok'::text CHECK (error_kind = ANY (ARRAY['ok'::text, 'unauthorized'::text, 'forbidden'::text, 'validation'::text, 'not_found'::text, 'conflict'::text, 'provider_deferred'::text, 'provider_rejected'::text, 'rate_limited'::text, 'internal'::text])),
  detail jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT edge_function_logs_pkey PRIMARY KEY (id),
  CONSTRAINT edge_function_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.wallet_order_backfill_report (
  order_id bigint NOT NULL,
  order_type text NOT NULL DEFAULT 'regular'::text,
  network text,
  offer_title text,
  amount numeric,
  backfill_status text NOT NULL,
  derived_provider_type text,
  derived_provider_size numeric,
  missing_fields ARRAY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT wallet_order_backfill_report_pkey PRIMARY KEY (order_id)
);
CREATE TABLE public.user_profile_drift_report (
  user_id uuid NOT NULL,
  email text,
  profile_role text,
  metadata_role text,
  profile_super_agent_id uuid,
  metadata_super_agent_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_profile_drift_report_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_profile_drift_report_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.duplicate_payment_reference_report (
  table_name text NOT NULL,
  payment_reference text NOT NULL,
  row_count bigint NOT NULL,
  order_ids ARRAY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT duplicate_payment_reference_report_pkey PRIMARY KEY (table_name, payment_reference)
);
CREATE TABLE public.held_order_expiry_log (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  order_id bigint NOT NULL,
  expired_at timestamp with time zone NOT NULL DEFAULT now(),
  agent_id uuid,
  super_agent_id uuid,
  order_created_at timestamp with time zone,
  held_since timestamp with time zone,
  amount numeric,
  base_amount numeric,
  recipient_phone text,
  payment_reference text,
  paystack_transaction_id text,
  paid_at timestamp with time zone,
  reason text NOT NULL DEFAULT 'held_window_elapsed'::text,
  refund_required boolean NOT NULL DEFAULT true,
  CONSTRAINT held_order_expiry_log_pkey PRIMARY KEY (id)
);