CREATE TABLE public.package_pricing (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  network text NOT NULL,
  type text NOT NULL,
  base_price numeric NOT NULL DEFAULT 0 CHECK (base_price >= 0),
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT package_pricing_network_type_unique UNIQUE (network, type)
);

CREATE INDEX IF NOT EXISTS idx_package_pricing_network ON public.package_pricing(network);
CREATE INDEX IF NOT EXISTS idx_package_pricing_active ON public.package_pricing(is_active);

-- Add RLS policies for package_pricing
ALTER TABLE public.package_pricing ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read active package pricing"
ON public.package_pricing
FOR SELECT
TO authenticated, anon
USING (is_active = true);

CREATE POLICY "Admins can insert package pricing"
ON public.package_pricing
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Admins can update package pricing"
ON public.package_pricing
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Admins can delete package pricing"
ON public.package_pricing
FOR DELETE
TO authenticated
USING (true);

-- Grant usage on the sequence
GRANT USAGE ON SEQUENCE package_pricing_id_seq TO authenticated, anon;
