BEGIN;

CREATE TABLE IF NOT EXISTS public.super_agent_wallets (
  super_agent_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  balance numeric NOT NULL DEFAULT 0 CHECK (balance >= 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.super_agent_wallet_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  super_agent_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  amount numeric NOT NULL CHECK (amount <> 0),
  balance_before numeric NOT NULL,
  balance_after numeric NOT NULL CHECK (balance_after >= 0),
  entry_type text NOT NULL CHECK (entry_type IN ('credit', 'debit')),
  reason text NOT NULL,
  reference text NOT NULL UNIQUE,
  order_id bigint,
  created_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_super_agent_wallet_ledger_agent_created
  ON public.super_agent_wallet_ledger (super_agent_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_super_agent_wallet_ledger_order
  ON public.super_agent_wallet_ledger (order_id);

ALTER TABLE public.super_agent_wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.super_agent_wallet_ledger ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS super_agent_wallet_read ON public.super_agent_wallets;
CREATE POLICY super_agent_wallet_read
  ON public.super_agent_wallets FOR SELECT
  TO authenticated
  USING (super_agent_id = auth.uid());

DROP POLICY IF EXISTS super_agent_wallet_ledger_read ON public.super_agent_wallet_ledger;
CREATE POLICY super_agent_wallet_ledger_read
  ON public.super_agent_wallet_ledger FOR SELECT
  TO authenticated
  USING (super_agent_id = auth.uid());

CREATE OR REPLACE FUNCTION public.debit_super_agent_wallet(
  p_super_agent_id uuid,
  p_amount numeric,
  p_reference text,
  p_order_id bigint DEFAULT NULL,
  p_reason text DEFAULT 'sub_agent_order'
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  wallet_row public.super_agent_wallets%ROWTYPE;
  existing_entry public.super_agent_wallet_ledger%ROWTYPE;
  new_balance numeric;
BEGIN
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'Wallet debit amount must be greater than zero';
  END IF;
  IF NULLIF(trim(p_reference), '') IS NULL THEN
    RAISE EXCEPTION 'Wallet debit reference is required';
  END IF;

  SELECT * INTO existing_entry
  FROM public.super_agent_wallet_ledger
  WHERE reference = p_reference
  LIMIT 1;

  IF FOUND THEN
    RETURN jsonb_build_object(
      'success', true,
      'already_processed', true,
      'balance', existing_entry.balance_after,
      'ledger_id', existing_entry.id
    );
  END IF;

  INSERT INTO public.super_agent_wallets (super_agent_id)
  VALUES (p_super_agent_id)
  ON CONFLICT (super_agent_id) DO NOTHING;

  SELECT * INTO wallet_row
  FROM public.super_agent_wallets
  WHERE super_agent_id = p_super_agent_id
  FOR UPDATE;

  IF wallet_row.balance < p_amount THEN
    RETURN jsonb_build_object(
      'success', false,
      'reason', 'insufficient_balance',
      'balance', wallet_row.balance,
      'required', p_amount
    );
  END IF;

  new_balance := wallet_row.balance - p_amount;

  UPDATE public.super_agent_wallets
  SET balance = new_balance, updated_at = now()
  WHERE super_agent_id = p_super_agent_id;

  INSERT INTO public.super_agent_wallet_ledger (
    super_agent_id,
    amount,
    balance_before,
    balance_after,
    entry_type,
    reason,
    reference,
    order_id
  ) VALUES (
    p_super_agent_id,
    -p_amount,
    wallet_row.balance,
    new_balance,
    'debit',
    p_reason,
    p_reference,
    p_order_id
  );

  RETURN jsonb_build_object(
    'success', true,
    'already_processed', false,
    'balance', new_balance
  );
END;
$$;

REVOKE ALL ON FUNCTION public.debit_super_agent_wallet(uuid, numeric, text, bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.debit_super_agent_wallet(uuid, numeric, text, bigint, text) TO service_role;

CREATE OR REPLACE FUNCTION public.credit_super_agent_wallet(
  p_super_agent_id uuid,
  p_amount numeric,
  p_reference text,
  p_reason text DEFAULT 'wallet_topup',
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  wallet_row public.super_agent_wallets%ROWTYPE;
  existing_entry public.super_agent_wallet_ledger%ROWTYPE;
  new_balance numeric;
BEGIN
  IF p_amount IS NULL OR p_amount <= 0 THEN
    RAISE EXCEPTION 'Wallet credit amount must be greater than zero';
  END IF;
  IF NULLIF(trim(p_reference), '') IS NULL THEN
    RAISE EXCEPTION 'Wallet credit reference is required';
  END IF;

  SELECT * INTO existing_entry
  FROM public.super_agent_wallet_ledger
  WHERE reference = p_reference
  LIMIT 1;

  IF FOUND THEN
    RETURN jsonb_build_object(
      'success', true,
      'already_processed', true,
      'balance', existing_entry.balance_after,
      'ledger_id', existing_entry.id
    );
  END IF;

  INSERT INTO public.super_agent_wallets (super_agent_id)
  VALUES (p_super_agent_id)
  ON CONFLICT (super_agent_id) DO NOTHING;

  SELECT * INTO wallet_row
  FROM public.super_agent_wallets
  WHERE super_agent_id = p_super_agent_id
  FOR UPDATE;

  new_balance := wallet_row.balance + p_amount;

  UPDATE public.super_agent_wallets
  SET balance = new_balance, updated_at = now()
  WHERE super_agent_id = p_super_agent_id;

  INSERT INTO public.super_agent_wallet_ledger (
    super_agent_id,
    amount,
    balance_before,
    balance_after,
    entry_type,
    reason,
    reference,
    metadata
  ) VALUES (
    p_super_agent_id,
    p_amount,
    wallet_row.balance,
    new_balance,
    'credit',
    p_reason,
    p_reference,
    COALESCE(p_metadata, '{}'::jsonb)
  );

  RETURN jsonb_build_object(
    'success', true,
    'already_processed', false,
    'balance', new_balance
  );
END;
$$;

REVOKE ALL ON FUNCTION public.credit_super_agent_wallet(uuid, numeric, text, text, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.credit_super_agent_wallet(uuid, numeric, text, text, jsonb) TO service_role;

COMMIT;
