BEGIN;

-- Stores the Paystack subaccount linked to a super agent so that
-- payments made by their sub-agents can be routed to that subaccount.
CREATE TABLE IF NOT EXISTS public.super_agent_paystack (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  super_agent_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  subaccount_code text NOT NULL,
  business_name text,
  settlement_bank text,
  settlement_bank_code text,
  account_number text,
  percentage_charge numeric,
  is_active boolean NOT NULL DEFAULT true,
  paystack_raw_response jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_super_agent_paystack_super_agent_id
  ON public.super_agent_paystack (super_agent_id);

CREATE INDEX IF NOT EXISTS idx_super_agent_paystack_subaccount_code
  ON public.super_agent_paystack (subaccount_code);

-- Track which subaccount a wallet topup was charged through so that
-- reconciliation against the Paystack dashboard remains auditable.
ALTER TABLE IF EXISTS public.wallet_topups
  ADD COLUMN IF NOT EXISTS paystack_subaccount_code text;

-- Track which subaccount (if any) fulfilled an agent order and
-- persist the settlement split metadata on the order itself.
ALTER TABLE IF EXISTS public.agent_orders
  ADD COLUMN IF NOT EXISTS paystack_subaccount_code text,
  ADD COLUMN IF NOT EXISTS paystack_transaction_id text,
  ADD COLUMN IF NOT EXISTS paystack_transaction_status text,
  ADD COLUMN IF NOT EXISTS paid_at timestamptz,
  ADD COLUMN IF NOT EXISTS channel text,
  ADD COLUMN IF NOT EXISTS bank text;

COMMIT;
