BEGIN;

CREATE TABLE IF NOT EXISTS public.normal_user_package_pricing (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id text,
  network text NOT NULL,
  type text NOT NULL,
  size numeric,
  base_price numeric NOT NULL DEFAULT 0 CHECK (base_price >= 0),
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT normal_user_package_pricing_network_type_unique
    UNIQUE (network, type)
);

ALTER TABLE public.normal_user_package_pricing
  ADD COLUMN IF NOT EXISTS package_id text,
  ADD COLUMN IF NOT EXISTS size numeric;

CREATE INDEX IF NOT EXISTS idx_normal_user_package_pricing_network
  ON public.normal_user_package_pricing(network);
CREATE INDEX IF NOT EXISTS idx_normal_user_package_pricing_active
  ON public.normal_user_package_pricing(is_active);
CREATE INDEX IF NOT EXISTS idx_normal_user_package_pricing_package_id
  ON public.normal_user_package_pricing(package_id);

ALTER TABLE public.normal_user_package_pricing ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read active normal user package pricing"
ON public.normal_user_package_pricing
FOR SELECT
TO authenticated, anon
USING (is_active = true);

CREATE POLICY "Admins can insert normal user package pricing"
ON public.normal_user_package_pricing
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Admins can update normal user package pricing"
ON public.normal_user_package_pricing
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Admins can delete normal user package pricing"
ON public.normal_user_package_pricing
FOR DELETE
TO authenticated
USING (true);

GRANT USAGE ON SEQUENCE normal_user_package_pricing_id_seq TO authenticated, anon;

COMMIT;