BEGIN;

-- Discounts that reduce the Jehuca (provider) API cost.
--
-- The admin sells each package at a base price, but the real cost is whatever
-- Jehuca charges. This table lets the admin knock a fixed amount off that live
-- provider price, so the recorded cost (and therefore margin, analytics and the
-- dispatch balance check) reflects the discounted figure rather than the
-- customer price.
--
-- One row per (audience, network, type). Audiences are 'super_agent' (sold via
-- package_pricing) and 'normal_user' (sold via normal_user_package_pricing).
-- The two audiences are configured independently.
CREATE TABLE IF NOT EXISTS public.api_cost_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  audience text NOT NULL DEFAULT 'super_agent'
    CHECK (audience IN ('super_agent', 'normal_user')),
  -- The Jehuca catalog package id. Preferred match key when present, because a
  -- display descriptor like "BIG TIME - 1GB" can be rebuilt inconsistently by
  -- different callers, whereas the provider id is stable.
  package_id text,
  network text NOT NULL,
  type text NOT NULL,
  -- Fixed amount subtracted from the live provider price. Stored as a positive
  -- number; the discount is the value itself. Kept separate from any "mode"
  -- flag so a zero discount is simply "no discount".
  discount numeric NOT NULL DEFAULT 0 CHECK (discount >= 0),
  -- Optional free-text so the admin can record why a discount exists / when it
  -- expires. Surfaced in the admin UI next to an active discount.
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES auth.users(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT api_cost_settings_audience_network_type_unique
    UNIQUE (audience, network, type)
);

CREATE INDEX IF NOT EXISTS idx_api_cost_settings_audience
  ON public.api_cost_settings(audience);
CREATE INDEX IF NOT EXISTS idx_api_cost_settings_network
  ON public.api_cost_settings(network);
CREATE INDEX IF NOT EXISTS idx_api_cost_settings_package_id
  ON public.api_cost_settings(audience, package_id);

ALTER TABLE public.api_cost_settings ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated can read api cost settings"
ON public.api_cost_settings
FOR SELECT
TO authenticated, anon
USING (true);

CREATE POLICY "Admins can insert api cost settings"
ON public.api_cost_settings
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Admins can update api cost settings"
ON public.api_cost_settings
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Admins can delete api cost settings"
ON public.api_cost_settings
FOR DELETE
TO authenticated
USING (true);

GRANT USAGE ON SEQUENCE api_cost_settings_id_seq TO authenticated, anon;

-- Orders snapshot the cost they were purchased at.
--
-- Immutable by design: editing a discount later must never rewrite the profit
-- of an order that was already placed. Historical rows fall back to the old
-- behaviour (cost == customer price) when api_cost is null.
ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS api_cost numeric,
  ADD COLUMN IF NOT EXISTS cost_source text;

ALTER TABLE public.agent_orders
  ADD COLUMN IF NOT EXISTS api_cost numeric,
  ADD COLUMN IF NOT EXISTS cost_source text;

-- Resolves the effective API cost for a package.
--
-- p_audience  'super_agent' | 'normal_user'
-- p_network   network, matched case-insensitively
-- p_type      package descriptor as shown in the admin pricing screens
-- p_package_id Jehuca catalog package id; when supplied it wins over the
--              descriptor match
-- p_live_cost the provider price in major units (i.e. already / 100)
-- p_fallback  cost to use when there is no live provider price
--
-- Precedence: active discount tier -> caller fallback. The discount is a fixed
-- amount off the live cost, clamped so the cost can never go below zero (a
-- generous discount must not turn into a negative cost that inflates profit).
--
-- Returns the cost plus its provenance so callers can record *why* a given
-- number was used.
CREATE OR REPLACE FUNCTION public.resolve_api_cost(
  p_audience text,
  p_network text,
  p_type text,
  p_package_id text,
  p_live_cost numeric,
  p_fallback numeric
)
RETURNS TABLE (
  api_cost numeric,
  cost_source text,
  discount numeric,
  notes text
)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  v_tier public.api_cost_settings%ROWTYPE;
  v_live numeric;
  v_base numeric;
  v_discount numeric := 0;
  v_audience text := COALESCE(NULLIF(TRIM(p_audience), ''), 'super_agent');
  v_package_id text := NULLIF(TRIM(p_package_id), '');
BEGIN
  -- Prefer a live provider price; fall back to whatever the caller supplied.
  v_live := COALESCE(p_live_cost, p_fallback);
  v_base := COALESCE(v_live, 0);

  -- A provider package id is the stable key, so prefer it when we have one.
  IF v_package_id IS NOT NULL THEN
    SELECT * INTO v_tier
    FROM public.api_cost_settings AS s
    WHERE s.audience = v_audience
      AND s.is_active = true
      AND s.package_id = v_package_id
    ORDER BY (s.discount > 0) DESC
    LIMIT 1;
  END IF;

  IF NOT FOUND THEN
    SELECT * INTO v_tier
    FROM public.api_cost_settings AS s
    WHERE s.audience = v_audience
      AND s.is_active = true
      AND UPPER(TRIM(s.network)) = UPPER(TRIM(p_network))
      AND UPPER(TRIM(s.type)) = UPPER(TRIM(p_type))
    ORDER BY (s.package_id IS NOT NULL) DESC
    LIMIT 1;
  END IF;

  IF FOUND THEN
    v_discount := COALESCE(v_tier.discount, 0);
  END IF;

  RETURN QUERY
  SELECT
    ROUND(GREATEST(v_base - v_discount, 0), 2),
    CASE
      WHEN v_discount > 0 THEN 'api_cost_discount'
      WHEN v_live IS NOT NULL THEN 'provider_price'
      ELSE 'fallback'
    END,
    v_discount,
    v_tier.notes;
END;
$$;

GRANT EXECUTE ON FUNCTION public.resolve_api_cost(text, text, text, text, numeric, numeric)
TO authenticated, anon, service_role;

COMMIT;
