BEGIN;

CREATE TABLE IF NOT EXISTS public.afa_registration_settings (
  id boolean PRIMARY KEY DEFAULT true CHECK (id),
  registration_fee numeric NOT NULL DEFAULT 0 CHECK (registration_fee >= 0),
  currency text NOT NULL DEFAULT 'GHS' CHECK (currency = 'GHS'),
  is_enabled boolean NOT NULL DEFAULT false,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.afa_registration_settings (id, registration_fee, currency, is_enabled)
VALUES (true, 0, 'GHS', false)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.afa_registrations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  registered_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  payer_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  assigned_super_agent_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  full_name text NOT NULL,
  phone text NOT NULL,
  id_type text NOT NULL CHECK (id_type IN ('National ID', 'Voters ID')),
  id_number text NOT NULL,
  town_city text NOT NULL,
  occupation text NOT NULL,
  additional_info jsonb NOT NULL DEFAULT '{}'::jsonb,
  fee_amount numeric NOT NULL CHECK (fee_amount >= 0),
  currency text NOT NULL DEFAULT 'GHS' CHECK (currency = 'GHS'),
  payment_method text NOT NULL CHECK (payment_method IN ('paystack', 'wallet')),
  status text NOT NULL DEFAULT 'pending_payment' CHECK (
    status IN ('pending_payment', 'paid', 'active', 'rejected', 'refunded', 'cancelled')
  ),
  payment_reference text UNIQUE,
  paystack_transaction_id text,
  paystack_transaction_status text,
  paid_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_afa_registrations_user_created
  ON public.afa_registrations (registered_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_afa_registrations_super_agent_created
  ON public.afa_registrations (assigned_super_agent_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_afa_registrations_user_status_created
  ON public.afa_registrations (registered_user_id, status, created_at DESC);

CREATE TABLE IF NOT EXISTS public.afa_payment_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  registration_id uuid NOT NULL REFERENCES public.afa_registrations(id) ON DELETE RESTRICT,
  payer_user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  amount numeric NOT NULL CHECK (amount <> 0),
  entry_type text NOT NULL DEFAULT 'registration_fee' CHECK (entry_type IN ('registration_fee', 'refund', 'adjustment')),
  payment_method text NOT NULL CHECK (payment_method IN ('paystack', 'wallet')),
  payment_reference text NOT NULL UNIQUE,
  paystack_transaction_id text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_afa_payment_ledger_created
  ON public.afa_payment_ledger (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_afa_payment_ledger_payer
  ON public.afa_payment_ledger (payer_user_id, created_at DESC);

ALTER TABLE public.afa_registration_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.afa_registrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.afa_payment_ledger ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS afa_settings_admin_read ON public.afa_registration_settings;
CREATE POLICY afa_settings_admin_read ON public.afa_registration_settings
  FOR SELECT TO authenticated
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'Admin'
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'Admin'
  );

DROP POLICY IF EXISTS afa_settings_admin_update ON public.afa_registration_settings;
CREATE POLICY afa_settings_admin_update ON public.afa_registration_settings
  FOR UPDATE TO authenticated
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'Admin'
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'Admin'
  )
  WITH CHECK (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'Admin'
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'Admin'
  );

DROP POLICY IF EXISTS afa_registrations_user_read ON public.afa_registrations;
CREATE POLICY afa_registrations_user_read ON public.afa_registrations
  FOR SELECT TO authenticated
  USING (
    registered_user_id = auth.uid()
    OR payer_user_id = auth.uid()
    OR assigned_super_agent_id = auth.uid()
    OR (auth.jwt() -> 'user_metadata' ->> 'role') = 'Admin'
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'Admin'
  );

DROP POLICY IF EXISTS afa_registrations_user_insert ON public.afa_registrations;
CREATE POLICY afa_registrations_user_insert ON public.afa_registrations
  FOR INSERT TO authenticated
  WITH CHECK (registered_user_id = auth.uid() AND payer_user_id = auth.uid());

DROP POLICY IF EXISTS afa_ledger_user_read ON public.afa_payment_ledger;
CREATE POLICY afa_ledger_user_read ON public.afa_payment_ledger
  FOR SELECT TO authenticated
  USING (
    payer_user_id = auth.uid()
    OR (auth.jwt() -> 'user_metadata' ->> 'role') = 'Admin'
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'Admin'
  );

-- Complete a Paystack-paid registration atomically and create the immutable ledger entry.
CREATE OR REPLACE FUNCTION public.finalize_afa_registration_payment(
  p_registration_id uuid,
  p_reference text,
  p_paystack_transaction_id text,
  p_paystack_status text,
  p_paid_at timestamptz
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  registration_row public.afa_registrations%ROWTYPE;
  existing_ledger public.afa_payment_ledger%ROWTYPE;
BEGIN
  SELECT * INTO registration_row
  FROM public.afa_registrations
  WHERE id = p_registration_id
  FOR UPDATE;

  IF NOT FOUND OR registration_row.payment_reference <> p_reference THEN
    RAISE EXCEPTION 'AFA registration or payment reference not found';
  END IF;

  SELECT * INTO existing_ledger
  FROM public.afa_payment_ledger
  WHERE payment_reference = p_reference
  LIMIT 1;

  IF FOUND THEN
    RETURN jsonb_build_object('success', true, 'already_processed', true, 'registration', registration_row);
  END IF;

  IF registration_row.status NOT IN ('pending_payment', 'paid', 'active') THEN
    RAISE EXCEPTION 'AFA registration is not payable';
  END IF;

  UPDATE public.afa_registrations
  SET status = 'active',
      paystack_transaction_id = p_paystack_transaction_id,
      paystack_transaction_status = p_paystack_status,
      paid_at = COALESCE(p_paid_at, now()),
      updated_at = now()
  WHERE id = p_registration_id
  RETURNING * INTO registration_row;

  INSERT INTO public.afa_payment_ledger (
    registration_id, payer_user_id, amount, payment_method,
    payment_reference, paystack_transaction_id, metadata
  ) VALUES (
    registration_row.id,
    registration_row.payer_user_id,
    registration_row.fee_amount,
    registration_row.payment_method,
    p_reference,
    p_paystack_transaction_id,
    jsonb_build_object('id_type', registration_row.id_type, 'currency', registration_row.currency)
  );

  RETURN jsonb_build_object('success', true, 'already_processed', false, 'registration', registration_row);
END;
$$;

REVOKE ALL ON FUNCTION public.finalize_afa_registration_payment(uuid, text, text, text, timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.finalize_afa_registration_payment(uuid, text, text, text, timestamptz) TO service_role;

-- Charge the Super Agent wallet and complete the registration in one transaction.
CREATE OR REPLACE FUNCTION public.pay_afa_registration_from_wallet(
  p_registration_id uuid,
  p_super_agent_id uuid,
  p_reference text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  registration_row public.afa_registrations%ROWTYPE;
  debit_result jsonb;
BEGIN
  SELECT * INTO registration_row
  FROM public.afa_registrations
  WHERE id = p_registration_id
  FOR UPDATE;

  IF NOT FOUND OR registration_row.status <> 'pending_payment' OR registration_row.payment_reference <> p_reference THEN
    RAISE EXCEPTION 'AFA registration is not payable';
  END IF;

  IF registration_row.payment_method <> 'wallet' THEN
    RAISE EXCEPTION 'AFA registration is not a wallet payment';
  END IF;

  SELECT * INTO debit_result
  FROM public.debit_super_agent_wallet(
    p_super_agent_id,
    registration_row.fee_amount,
    p_reference,
    NULL,
    'afa_registration'
  );

  IF NOT (debit_result ->> 'success')::boolean THEN
    RETURN jsonb_build_object('success', false, 'reason', debit_result ->> 'reason', 'debit', debit_result);
  END IF;

  UPDATE public.afa_registrations
  SET status = 'active', paid_at = now(), updated_at = now()
  WHERE id = p_registration_id
  RETURNING * INTO registration_row;

  INSERT INTO public.afa_payment_ledger (
    registration_id, payer_user_id, amount, payment_method, payment_reference, metadata
  ) VALUES (
    registration_row.id,
    registration_row.payer_user_id,
    registration_row.fee_amount,
    'wallet',
    p_reference,
    jsonb_build_object('wallet_debit', debit_result, 'currency', registration_row.currency)
  ) ON CONFLICT (payment_reference) DO NOTHING;

  RETURN jsonb_build_object('success', true, 'already_processed', false, 'registration', registration_row, 'debit', debit_result);
END;
$$;

REVOKE ALL ON FUNCTION public.pay_afa_registration_from_wallet(uuid, uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.pay_afa_registration_from_wallet(uuid, uuid, text) TO service_role;

COMMIT;
