BEGIN;

CREATE TABLE IF NOT EXISTS public.payment_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id uuid REFERENCES auth.users(id),
  order_id bigint,
  order_type text NOT NULL CHECK (order_type IN ('regular', 'agent')),
  payment_reference text NOT NULL UNIQUE,
  paystack_transaction_id text,
  paystack_transaction_status text,
  gross_amount numeric NOT NULL DEFAULT 0,
  base_amount numeric NOT NULL DEFAULT 0,
  agent_markup numeric NOT NULL DEFAULT 0,
  transaction_fee numeric NOT NULL DEFAULT 0,
  main_account_amount numeric NOT NULL DEFAULT 0,
  super_agent_amount numeric NOT NULL DEFAULT 0,
  agent_net numeric NOT NULL DEFAULT 0,
  super_agent_id uuid REFERENCES auth.users(id),
  settlement_status text NOT NULL DEFAULT 'pending'
    CHECK (settlement_status IN ('pending', 'settled', 'released', 'failed')),
  status text NOT NULL DEFAULT 'success',
  network text,
  offer_title text,
  recipient_phone text,
  channel text,
  bank text,
  paystack_subaccount_code text,
  jehuca_order_id text,
  jehuca_order_status text,
  jehuca_response jsonb
);

CREATE INDEX IF NOT EXISTS idx_payment_transactions_created_at
  ON public.payment_transactions (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_super_agent_id
  ON public.payment_transactions (super_agent_id);
CREATE INDEX IF NOT EXISTS idx_payment_transactions_order
  ON public.payment_transactions (order_type, order_id);

ALTER TABLE IF EXISTS public.agent_orders
  ADD COLUMN IF NOT EXISTS base_amount numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS agent_markup numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS transaction_fee numeric DEFAULT 0,
  ADD COLUMN IF NOT EXISTS main_account_amount numeric DEFAULT 0;

ALTER TABLE IF EXISTS public.orders
  ADD COLUMN IF NOT EXISTS jehuca_order_id text,
  ADD COLUMN IF NOT EXISTS jehuca_order_status text,
  ADD COLUMN IF NOT EXISTS jehuca_response jsonb;

ALTER TABLE public.payment_transactions ENABLE ROW LEVEL SECURITY;

CREATE POLICY payment_transactions_admin_read
  ON public.payment_transactions FOR SELECT
  TO authenticated
  USING (
    (auth.jwt() -> 'user_metadata' ->> 'role') = 'Admin'
    OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'Admin'
  );

CREATE POLICY payment_transactions_super_agent_read
  ON public.payment_transactions FOR SELECT
  TO authenticated
  USING (super_agent_id = auth.uid());

CREATE POLICY payment_transactions_user_insert
  ON public.payment_transactions FOR INSERT
  TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY payment_transactions_user_update
  ON public.payment_transactions FOR UPDATE
  TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

COMMIT;