BEGIN;

CREATE TABLE IF NOT EXISTS public.super_agent_tiers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  super_agent_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT super_agent_tiers_name_unique UNIQUE (super_agent_id, name)
);

CREATE INDEX IF NOT EXISTS idx_super_agent_tiers_super_agent_id
  ON public.super_agent_tiers (super_agent_id);

COMMIT;
